# Generated by Django 5.2.4 on 2025-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/pfp_placeholder.jpeg', upload_to='profile_pictures'),
        ),
    ]
